---
- name: "Install containerd (debian)"
  apt:
    pkg: "{{ install_containerd_packages[(ansible_os_family | lower) + '_' + (ansible_architecture | lower)] | json_query('[].name')}}"
    update_cache: yes
    install_recommends: no
  register: installed_containerd_packages
  when:
    - "(ansible_os_family | lower) == 'debian'"
  tags:
    - "containerd"
- name: "Pin containerd (debian)"
  environment:
    PATH: "{{ ansible_env.PATH }}:/sbin:/usr/sbin"
  shell: >-
    apt-mark hold {{ item }}
  with_items: "{{ install_containerd_packages[(ansible_os_family | lower) + '_' + (ansible_architecture | lower)] | json_query('[?hold==`true`].name')}}"
  when:
    - "(ansible_os_family | lower) == 'debian'"
    - "installed_containerd_packages.changed"
  tags:
    - "containerd"
